-- Create Orders Table
create table public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer_name text not null,
  email text,
  phone text,
  shipping_address text,
  status text not null default 'pending' check (status in ('pending', 'processing', 'handed_over', 'delivered', 'cancelled')),
  total numeric(10,2) not null default 0
);

-- Create Order Items Table (Optional, for storing details of each product in an order)
create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade not null,
  product_id bigint references public.products(id), -- Assuming you have a products table
  product_name text not null,
  quantity integer not null default 1,
  price numeric(10,2) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Create policies (Adjust as needed for your auth setup)
-- Allow public access for now (or restrict to authenticated users/admin)
create policy "Enable read access for all users" on public.orders for select using (true);
create policy "Enable insert access for all users" on public.orders for insert with check (true);
create policy "Enable update access for all users" on public.orders for update using (true);

create policy "Enable read access for all users" on public.order_items for select using (true);
create policy "Enable insert access for all users" on public.order_items for insert with check (true);
