-- Enable the UUID extension (optional but good practice)
create extension if not exists "uuid-ossp";

-- ==========================================
-- 1. PRODUCTS TABLE
-- ==========================================

-- Create products table
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  description text,
  weight text,
  origin text,
  shape text,
  treatment text,
  clarity text,
  color text,
  cut text,
  badge text,
  badge_color text,
  category text,
  images text[],
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.products enable row level security;

-- Create Policy: Allow read access to everyone
create policy "Allow public read access on products"
  on public.products
  for select
  to public
  using (true);

-- Seed Data for Products
INSERT INTO public.products (name, price, description, weight, origin, shape, treatment, clarity, color, cut, badge, badge_color, category, images) VALUES
(
  'Royal Blue Ceylon Sapphire',
  4250,
  'An exceptional 2.14 carat oval cut sapphire featuring the coveted ''Royal Blue'' hue. Sourced ethically from the mines of Ratnapura, Sri Lanka. This stone exhibits excellent clarity and brilliance, perfect for a custom engagement ring or investment piece.',
  '2.14 Carats',
  'Sri Lanka (Ceylon)',
  'Oval Mixed Cut',
  'Heat Only',
  'VVS1 - Eye Clean',
  'Royal Blue',
  'Cushion Cut',
  'New Arrival',
  'bg-[#1152d4]/90',
  'Blue Sapphire',
  ARRAY['/collections/blue/1.png']
),
(
  'Vivid Pink Sapphire',
  3100,
  'A stunning 1.85 carat pink sapphire with exceptional vivid color saturation. This elegant oval cut gemstone showcases the finest pink hues found in Ceylon sapphires. Heat-treated to enhance its natural beauty while maintaining its authentic character.',
  '1.85 Carats',
  'Sri Lanka (Ceylon)',
  'Oval Cut',
  'Heated',
  'VS - Very Good',
  'Vivid Pink',
  'Oval Cut',
  NULL,
  NULL,
  'Pink Sapphire',
  ARRAY['/collections/pink/1.png']
),
(
  'Burma Ruby',
  8500,
  'An extraordinary 1.50 carat round Burmese ruby displaying the legendary ''pigeon blood'' red color. This natural, unheated ruby is exceptionally rare and represents the pinnacle of ruby quality. A true collector''s gemstone with impeccable provenance.',
  '1.50 Carats',
  'Myanmar (Burma)',
  'Round Brilliant Cut',
  'Natural',
  'VVS - Excellent',
  'Pigeon Blood Red',
  'Round Cut',
  'Rare Find',
  'bg-rose-600/90',
  'Ruby',
  ARRAY['/collections/rubie/1.png']
),
(
  'Canary Yellow Sapphire',
  5900,
  'A magnificent 3.05 carat yellow sapphire with a captivating canary yellow hue. The emerald cut showcases the stone''s exceptional clarity and vibrant color. This natural, unheated sapphire is perfect for statement jewelry or as an astrological gemstone.',
  '3.05 Carats',
  'Sri Lanka (Ceylon)',
  'Emerald Cut',
  'Natural',
  'VS1 - Eye Clean',
  'Canary Yellow',
  'Emerald Cut',
  NULL,
  NULL,
  'Yellow Sapphire',
  ARRAY['/collections/yellow/1.png']
),
(
  'Peacock Teal Sapphire',
  2800,
  'A mesmerizing 1.95 carat teal sapphire showcasing a unique peacock-inspired color blend of blue and green. The radiant cut enhances the stone''s exceptional brilliance and color play. Heat-treated to bring out its captivating hues.',
  '1.95 Carats',
  'Sri Lanka (Ceylon)',
  'Radiant Cut',
  'Heated',
  'VS - Very Good',
  'Peacock Teal',
  'Radiant Cut',
  NULL,
  NULL,
  'Teal Sapphire',
  ARRAY['/collections/green/1.png']
),
(
  'Lavender Spinel',
  1950,
  'A delightful 2.50 carat lavender spinel with excellent transparency and a soft, romantic color. The cushion cut perfectly complements the stone''s gentle hue. This natural, untreated spinel is a rare and beautiful alternative to traditional gemstones.',
  '2.50 Carats',
  'Sri Lanka (Ceylon)',
  'Cushion Cut',
  'Natural',
  'VVS - Excellent',
  'Lavender',
  'Cushion Cut',
  NULL,
  NULL,
  'Spinel',
  ARRAY['/collections/green/1.png']
),
(
  'Rare Padparadscha Sapphire',
  12500,
  'A breathtaking 2.01 carat Padparadscha sapphire, exhibiting the perfect marriage of lotus pink and sunset orange. This natural, unheated stone is among the rarest of all sapphires. A true masterpiece of nature from the gem fields of Sri Lanka.',
  '2.01 Carats',
  'Sri Lanka (Ceylon)',
  'Oval Cut',
  'Natural',
  'VVS2 - Eye Clean',
  'Pinkish Orange',
  'Oval Cut',
  'Investment Grade',
  'bg-purple-600/90',
  'Padparadscha',
  ARRAY['/collections/padmaracha/1.png']
),
(
  'Cat''s Eye Chrysoberyl',
  4800,
  'An exceptional 5.40 carat cat''s eye chrysoberyl with a sharp, well-defined ''milk and honey'' effect. This natural gemstone exhibits a strong chatoyancy that glides across the surface. A rare specimen of exceptional quality and clarity.',
  '5.40 Carats',
  'Sri Lanka (Ceylon)',
  'Cabochon',
  'Natural',
  'Excellent Chatoyancy',
  'Honey Green',
  'Cabochon',
  'Unique',
  'bg-emerald-600/90',
  'Cats Eye',
  ARRAY['/collections/cats-eye/1.png']
),
(
  'Deep Red Garnet',
  850,
  'A magnificent 3.25 carat deep red garnet with exceptional clarity and a rich, velvety color. This natural, unheated gemstone is sourced from the fertile lands of Ratnapura, Sri Lanka. Its brilliant cut ensures a captivating play of light, making it a perfect center stone for elegant jewelry.',
  '3.25 Carats',
  'Sri Lanka',
  'Round Brilliant',
  'Natural',
  'VVS - Eye Clean',
  'Deep Red',
  'Round Cut',
  'Classic',
  'bg-red-700/90',
  'Fine Gems',
  ARRAY['/collections/fine-gems/garnet.png']
),
(
  'Sky Blue Topaz',
  650,
  'A breathtaking 4.50 carat sky blue topaz featuring a serene and clear blue hue. This expertly cut emerald-shaped gemstone exhibits remarkable brilliance and transparency. Its refreshing color and durable nature make it an ideal choice for daily wear jewelry.',
  '4.50 Carats',
  'Brazil',
  'Emerald Cut',
  'Irradiated (Standard)',
  'IF - Flawless',
  'Sky Blue',
  'Emerald Cut',
  'Popular',
  'bg-sky-500/90',
  'Fine Gems',
  ARRAY['/collections/fine-gems/topaz.png']
),
(
  'Vibrant Green Peridot',
  920,
  'A stunning 2.80 carat peridot with a vivid, olive-green glow. Known as the ''gem of the sun'', this natural gemstone is carefully cut to maximize its unique double refraction and brilliance. A fresh and energetic piece for any gemstone collection.',
  '2.80 Carats',
  'Pakistan',
  'Oval Cut',
  'Natural',
  'VS - Very Good',
  'Olive Green',
  'Oval Cut',
  'Organic',
  'bg-lime-600/90',
  'Fine Gems',
  ARRAY['/collections/fine-gems/peridot.png']
),
(
  'Golden Citrine',
  580,
  'A radiant 5.10 carat golden citrine that captures the essence of sunshine. This cushion-cut gemstone displays a warm, honey-yellow hue with excellent transparency. Its vibrant energy and beautiful color make it a favorite for statement rings and pendants.',
  '5.10 Carats',
  'Brazil',
  'Cushion Cut',
  'Heated (Standard)',
  'VVS - Eye Clean',
  'Golden Yellow',
  'Cushion Cut',
  'Warmth',
  'bg-amber-500/90',
  'Fine Gems',
  ARRAY['/collections/fine-gems/citrine.png']
),
(
  'Royal Purple Amethyst',
  750,
  'An exquisite 3.90 carat royal purple amethyst with deep, saturated color and flashes of rose-red. This heart-shaped gemstone is meticulously cut to showcase its natural beauty and exceptional clarity. A symbol of royalty and peace.',
  '3.90 Carats',
  'Uruguay',
  'Heart Cut',
  'Natural',
  'VVS1 - Eye Clean',
  'Royal Purple',
  'Heart Cut',
  'Elegant',
  'bg-purple-800/90',
  'Fine Gems',
  ARRAY['/collections/fine-gems/amethyst.png']
);


-- ==========================================
-- 2. SLIDESHOW IMAGES TABLE
-- ==========================================

-- Create slideshow_images table
create table public.slideshow_images (
  id bigint generated by default as identity primary key,
  image_url text not null,
  alt_text text,
  sort_order integer default 0,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for slideshow_images
alter table public.slideshow_images enable row level security;

-- Create Policy: Allow public read access on slideshow_images
create policy "Allow public read access on slideshow_images"
  on public.slideshow_images
  for select
  to public
  using (true);

-- Seed Data for Slideshow Images (using placeholders, replace with Cloudinary links later)
INSERT INTO public.slideshow_images (image_url, sort_order) VALUES
('/hero/hero.jpeg', 1),
('/hero/hero1.jpeg', 2),
('/hero/hero3.jpeg', 3),
('/hero/hero4.jpeg', 4);
